M48
; DRILL file {KiCad (7.0.0)} date Mon Mar  6 13:00:38 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T13:00:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X5.15Y-3.2
X5.15Y-3.8
X6.75Y-3.2
X6.75Y-3.8
T0
M30
