M48
; DRILL file {KiCad (7.0.0)} date Wed Mar  8 14:36:54 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-08T14:36:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
%
G90
G05
T1
X130.81Y-81.28
X130.81Y-96.52
X171.45Y-81.28
X171.45Y-96.52
T0
M30
